### ISSUE TITLE
请问训练自己的数据，input_size和text_size分别表示什么？

### ISSUE THREAD

**Issue by wiener0zyj** [HaozhengLi/EAST_ICPR#11]
问题1：样本图片是否必须是正方形的，比如512*512的？我的样本图片是3456*4608大小的可以嘛？
问题2：input_size表示的是什么意思，正方形图片的一个边的像素吗？
问题3：text_size表示的是什么意思，为什么和input_size一样都是512?

**Comment by HaozhengLi** [comment]
1：否；可以。
2、3：是算法归一化（resize）的输入图片大小。
