### ISSUE TITLE
请问res101混合数据集的那个模型为什么不行运行呢？

### ISSUE THREAD

**Issue by HeYilong0316** [HaozhengLi/EAST_ICPR#2]
![image](https://user-images.githubusercontent.com/26954768/40056195-26abf1fe-587d-11e8-9dd1-fc9eb2e2b6b4.png)

**Comment by HaozhengLi** [comment]
Hello @18817835685 

If you want to change the model, please change the codes according to <[How can i test Resnet101 backbone based model? #1](https://github.com/HaozhengLi/EAST_ICPR/issues/1)>.

**Comment by 18817835685** [comment]
Thank you very much 😂😂

**Comment by HeYilong0316** [comment]
@HaozhengLi   Thank you very much😂😂
