### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Zumbalamambo** [HaozhengLi/EAST_ICPR#4]
The link for shared pretrained model isnt working. Can you please share the pretrained model?

**Comment by HaozhengLi** [comment]
hello @Zumbalamambo 

Before the [ICPR MTWI 2018 CHALLENGE](https://tianchi.aliyun.com/competition/introduction.htm?spm=5176.100066.0.0.144ed780W1xl9s&raceId=231651) has completed, some pre-trained model will not be shared. Because I join the CHALLENGE too.

I am sorry.

**Comment by arsalan993** [comment]
Can you make your pretrained model available @HaozhengLi
