### ISSUE TITLE
Can pre-trained models be uploaded to Google Drive? BaiduYun does not work in some country.

### ISSUE THREAD

**Issue by arsalan993** [HaozhengLi/EAST_ICPR#5]
I guess competition is completed on  2018/05/23

**Comment by HaozhengLi** [comment]
hello @arsalan993 

You are right. So all the pre-trained models are available now.

**Comment by arsalan993** [comment]
@HaozhengLi  still i am unable to down load it ... can you mention below the download link for 1035K
.. problem is as soon as i click on 1035K it opens up bady page with error..

**Comment by HaozhengLi** [comment]
My colleague and I both test the link and it does work.

Maybe you can straightly enter the website: https://pan.baidu.com/s/1jfjDxS4uknVavaOMO_wZQA

**Comment by arsalan993** [comment]
Baidu does not allow download outside China i guess.. 
Sir is it possible if you could upload or transfer the model to google drive or drop box..
I have even tried making Baidu account and then downloading it still 404 error.. 
Problem is not just with this specific link but all with all other Baidu download links..

**Comment by HaozhengLi** [comment]
But I can not open Google / Google Drive in China, it is 404 error in my country.

So I am sorry I can not help you.

Maybe you can try a VPN, or ask the people who has download successfully.

**Comment by arsalan993** [comment]
What about DropBox ,  or Google one drive ...

**Comment by HaozhengLi** [comment]
The update speed of such websites are about 1kb/s in China. That is why I choose BaiduYun.

Again I suggest you to use a VPN for BaiduYun, or ask those who have downloaded the models successfully.

So sorry again, I can not help you now.

But I will continue to try uploading models to such error / slow websites. Once I success, I will @ you at once.

**Comment by arsalan993** [comment]
Sir i can access this ..  can you?
https://www.jianguoyun.com/

**Comment by wajahat57** [comment]
You can use 'baidul-dl' add-on in chrome. It will help you download the files

**Comment by DhavalNiphade** [comment]
@arsalan993 you can use this [guide](https://www.reddit.com/r/Piracy/comments/by70qt/guide_to_baidu_account_creationdownloading_from/) to create a Baidu temporary baidu account and download the pre-trained models.

The process is tricky cuz of the language barrier, but quick if you follow the steps.
