### ISSUE TITLE
ICPR数据集

### ISSUE THREAD

**Issue by ghost** [HaozhengLi/EAST_ICPR#8]
作者你好，由于ICPR比赛结束了，我希望能下载训练和测试数据集，能否提供下ICPR的测试数据集的下载链接或者云盘链接，谢谢

**Comment by HaozhengLi** [comment]
https://pan.baidu.com/s/1OBDwzGz0lJUjlooWZGyeHQ

**Comment by sneffort** [comment]
作者您好，想问下您云盘中的数据集是用您matlab数据已经处理好的么，还是需要重新处理一遍呢？谢谢 @HaozhengLi

**Comment by HaozhengLi** [comment]
The raw data set.

**Comment by sneffort** [comment]
请问您训练1035k那个提交线上成绩的模型，用了多久，是几卡什么配置的机器训练的呢。我这边感觉训练特别缓慢。谢谢您的回答。 @HaozhengLi

**Comment by HaozhengLi** [comment]
> 请问您训练1035k那个提交线上成绩的模型，用了多久，是几卡什么配置的机器训练的呢。我这边感觉训练特别缓慢。谢谢您的回答。 @HaozhengLi

GPU Quadro M5000 x1 for about one week. By the way CPU dose not matter.

**Comment by tianxingyzxq** [comment]
> https://pan.baidu.com/s/1OBDwzGz0lJUjlooWZGyeHQ

你好，这个好像是ICDAR2017的数据，不是ICPR的，能提供下ICRP的数据集吗，谢谢 @HaozhengLi

**Comment by zobeirraisi** [comment]
این هم به اون ...
نمیشه انگلیسی بنویسید تا ما هم بفهمیم؟
